// Generated by scripts/generate-demo-media.py.
export const demoAudio = {
  "quiz-intro": {
    "audioUrl": "demo/audio/quiz-intro.wav",
    "durationInSeconds": 3.323809523809524,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.411655,
        "text": "Three"
      },
      {
        "startInSeconds": 0.436644,
        "endInSeconds": 0.780952,
        "text": "quick"
      },
      {
        "startInSeconds": 0.805941,
        "endInSeconds": 1.409932,
        "text": "questions"
      },
      {
        "startInSeconds": 1.434921,
        "endInSeconds": 1.84966,
        "text": "about"
      },
      {
        "startInSeconds": 1.874649,
        "endInSeconds": 2.142585,
        "text": "our"
      },
      {
        "startInSeconds": 2.167574,
        "endInSeconds": 2.54839,
        "text": "solar"
      },
      {
        "startInSeconds": 2.573379,
        "endInSeconds": 3.02381,
        "text": "system."
      }
    ]
  },
  "quiz-outro": {
    "audioUrl": "demo/audio/quiz-outro.wav",
    "durationInSeconds": 3.769433106575964,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.424898,
        "text": "How"
      },
      {
        "startInSeconds": 0.449887,
        "endInSeconds": 0.757188,
        "text": "many"
      },
      {
        "startInSeconds": 0.782177,
        "endInSeconds": 1.049252,
        "text": "did"
      },
      {
        "startInSeconds": 1.07424,
        "endInSeconds": 1.360317,
        "text": "you"
      },
      {
        "startInSeconds": 1.385306,
        "endInSeconds": 1.663583,
        "text": "get"
      },
      {
        "startInSeconds": 1.688571,
        "endInSeconds": 2.016735,
        "text": "right?"
      },
      {
        "startInSeconds": 2.196735,
        "endInSeconds": 2.703129,
        "text": "Thanks"
      },
      {
        "startInSeconds": 2.728118,
        "endInSeconds": 3.05805,
        "text": "for"
      },
      {
        "startInSeconds": 3.083039,
        "endInSeconds": 3.469433,
        "text": "playing!"
      }
    ]
  },
  "quiz-q1": {
    "audioUrl": "demo/audio/quiz-q1.wav",
    "durationInSeconds": 3.2491156462585034,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.456236,
        "text": "Which"
      },
      {
        "startInSeconds": 0.481224,
        "endInSeconds": 0.871111,
        "text": "planet"
      },
      {
        "startInSeconds": 0.8961,
        "endInSeconds": 1.174921,
        "text": "is"
      },
      {
        "startInSeconds": 1.199909,
        "endInSeconds": 1.564399,
        "text": "known"
      },
      {
        "startInSeconds": 1.589388,
        "endInSeconds": 1.911746,
        "text": "as"
      },
      {
        "startInSeconds": 1.936735,
        "endInSeconds": 2.170703,
        "text": "the"
      },
      {
        "startInSeconds": 2.195692,
        "endInSeconds": 2.530975,
        "text": "red"
      },
      {
        "startInSeconds": 2.555964,
        "endInSeconds": 2.949116,
        "text": "planet?"
      }
    ]
  },
  "quiz-a1": {
    "audioUrl": "demo/audio/quiz-a1.wav",
    "durationInSeconds": 0.8729705215419501,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.572971,
        "text": "Mars."
      }
    ]
  },
  "quiz-c1": {
    "audioUrl": "demo/audio/quiz-c1.wav",
    "durationInSeconds": 3.397687074829932,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.470068,
        "text": "Iron"
      },
      {
        "startInSeconds": 0.495057,
        "endInSeconds": 0.956508,
        "text": "minerals"
      },
      {
        "startInSeconds": 0.981497,
        "endInSeconds": 1.274104,
        "text": "give"
      },
      {
        "startInSeconds": 1.299093,
        "endInSeconds": 1.616463,
        "text": "its"
      },
      {
        "startInSeconds": 1.641451,
        "endInSeconds": 2.107937,
        "text": "surface"
      },
      {
        "startInSeconds": 2.132925,
        "endInSeconds": 2.377732,
        "text": "a"
      },
      {
        "startInSeconds": 2.402721,
        "endInSeconds": 2.774875,
        "text": "rusty"
      },
      {
        "startInSeconds": 2.799864,
        "endInSeconds": 3.097687,
        "text": "color."
      }
    ]
  },
  "quiz-q2": {
    "audioUrl": "demo/audio/quiz-q2.wav",
    "durationInSeconds": 3.15265306122449,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.456236,
        "text": "Which"
      },
      {
        "startInSeconds": 0.481224,
        "endInSeconds": 0.871111,
        "text": "planet"
      },
      {
        "startInSeconds": 0.8961,
        "endInSeconds": 1.281179,
        "text": "has"
      },
      {
        "startInSeconds": 1.306168,
        "endInSeconds": 1.540136,
        "text": "the"
      },
      {
        "startInSeconds": 1.565125,
        "endInSeconds": 1.939864,
        "text": "most"
      },
      {
        "startInSeconds": 1.964853,
        "endInSeconds": 2.376871,
        "text": "famous"
      },
      {
        "startInSeconds": 2.401859,
        "endInSeconds": 2.852653,
        "text": "rings?"
      }
    ]
  },
  "quiz-a2": {
    "audioUrl": "demo/audio/quiz-a2.wav",
    "durationInSeconds": 0.829342403628118,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.529342,
        "text": "Saturn."
      }
    ]
  },
  "quiz-c2": {
    "audioUrl": "demo/audio/quiz-c2.wav",
    "durationInSeconds": 3.2399546485260773,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.43737,
        "text": "Its"
      },
      {
        "startInSeconds": 0.462358,
        "endInSeconds": 0.913288,
        "text": "rings"
      },
      {
        "startInSeconds": 0.938277,
        "endInSeconds": 1.226621,
        "text": "are"
      },
      {
        "startInSeconds": 1.25161,
        "endInSeconds": 1.621587,
        "text": "made"
      },
      {
        "startInSeconds": 1.646576,
        "endInSeconds": 1.920544,
        "text": "of"
      },
      {
        "startInSeconds": 1.945533,
        "endInSeconds": 2.247846,
        "text": "ice"
      },
      {
        "startInSeconds": 2.272834,
        "endInSeconds": 2.593016,
        "text": "and"
      },
      {
        "startInSeconds": 2.618005,
        "endInSeconds": 2.939955,
        "text": "rock."
      }
    ]
  },
  "quiz-q3": {
    "audioUrl": "demo/audio/quiz-q3.wav",
    "durationInSeconds": 2.686077097505669,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.417732,
        "text": "What"
      },
      {
        "startInSeconds": 0.442721,
        "endInSeconds": 0.721542,
        "text": "is"
      },
      {
        "startInSeconds": 0.746531,
        "endInSeconds": 0.980499,
        "text": "the"
      },
      {
        "startInSeconds": 1.005488,
        "endInSeconds": 1.389887,
        "text": "name"
      },
      {
        "startInSeconds": 1.414875,
        "endInSeconds": 1.688844,
        "text": "of"
      },
      {
        "startInSeconds": 1.713832,
        "endInSeconds": 1.981769,
        "text": "our"
      },
      {
        "startInSeconds": 2.006757,
        "endInSeconds": 2.386077,
        "text": "star?"
      }
    ]
  },
  "quiz-a3": {
    "audioUrl": "demo/audio/quiz-a3.wav",
    "durationInSeconds": 1.0178684807256235,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.353968,
        "text": "The"
      },
      {
        "startInSeconds": 0.378957,
        "endInSeconds": 0.717868,
        "text": "Sun."
      }
    ]
  },
  "quiz-c3": {
    "audioUrl": "demo/audio/quiz-c3.wav",
    "durationInSeconds": 3.6141043083900226,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.43737,
        "text": "Its"
      },
      {
        "startInSeconds": 0.462358,
        "endInSeconds": 0.797551,
        "text": "light"
      },
      {
        "startInSeconds": 0.82254,
        "endInSeconds": 1.207392,
        "text": "takes"
      },
      {
        "startInSeconds": 1.232381,
        "endInSeconds": 1.64712,
        "text": "about"
      },
      {
        "startInSeconds": 1.672109,
        "endInSeconds": 1.933333,
        "text": "eight"
      },
      {
        "startInSeconds": 1.958322,
        "endInSeconds": 2.387937,
        "text": "minutes"
      },
      {
        "startInSeconds": 2.412925,
        "endInSeconds": 2.65619,
        "text": "to"
      },
      {
        "startInSeconds": 2.681179,
        "endInSeconds": 3.030748,
        "text": "reach"
      },
      {
        "startInSeconds": 3.055737,
        "endInSeconds": 3.314104,
        "text": "Earth."
      }
    ]
  },
  "ranking-three": {
    "audioUrl": "demo/audio/ranking-three.wav",
    "durationInSeconds": 4.71437641723356,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.553832,
        "text": "Number"
      },
      {
        "startInSeconds": 0.578821,
        "endInSeconds": 0.870476,
        "text": "three."
      },
      {
        "startInSeconds": 1.050476,
        "endInSeconds": 1.579683,
        "text": "Reusable"
      },
      {
        "startInSeconds": 1.604671,
        "endInSeconds": 2.056372,
        "text": "scenes"
      },
      {
        "startInSeconds": 2.081361,
        "endInSeconds": 2.404853,
        "text": "keep"
      },
      {
        "startInSeconds": 2.429841,
        "endInSeconds": 2.674649,
        "text": "a"
      },
      {
        "startInSeconds": 2.699637,
        "endInSeconds": 3.32839,
        "text": "consistent"
      },
      {
        "startInSeconds": 3.353379,
        "endInSeconds": 3.788435,
        "text": "visual"
      },
      {
        "startInSeconds": 3.813424,
        "endInSeconds": 4.414376,
        "text": "language."
      }
    ]
  },
  "ranking-two": {
    "audioUrl": "demo/audio/ranking-two.wav",
    "durationInSeconds": 4.5547392290249435,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.553832,
        "text": "Number"
      },
      {
        "startInSeconds": 0.578821,
        "endInSeconds": 0.828254,
        "text": "two."
      },
      {
        "startInSeconds": 1.008254,
        "endInSeconds": 1.378957,
        "text": "Word"
      },
      {
        "startInSeconds": 1.403946,
        "endInSeconds": 1.894331,
        "text": "timings"
      },
      {
        "startInSeconds": 1.91932,
        "endInSeconds": 2.253787,
        "text": "turn"
      },
      {
        "startInSeconds": 2.278776,
        "endInSeconds": 2.792653,
        "text": "narration"
      },
      {
        "startInSeconds": 2.817642,
        "endInSeconds": 3.136553,
        "text": "into"
      },
      {
        "startInSeconds": 3.161542,
        "endInSeconds": 3.61737,
        "text": "readable"
      },
      {
        "startInSeconds": 3.642358,
        "endInSeconds": 4.254739,
        "text": "captions."
      }
    ]
  },
  "ranking-one": {
    "audioUrl": "demo/audio/ranking-one.wav",
    "durationInSeconds": 4.70671201814059,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.553832,
        "text": "Number"
      },
      {
        "startInSeconds": 0.578821,
        "endInSeconds": 0.919683,
        "text": "one."
      },
      {
        "startInSeconds": 1.099683,
        "endInSeconds": 1.34449,
        "text": "A"
      },
      {
        "startInSeconds": 1.369478,
        "endInSeconds": 1.784308,
        "text": "shared"
      },
      {
        "startInSeconds": 1.809297,
        "endInSeconds": 2.290522,
        "text": "timeline"
      },
      {
        "startInSeconds": 2.31551,
        "endInSeconds": 2.719093,
        "text": "keeps"
      },
      {
        "startInSeconds": 2.744082,
        "endInSeconds": 3.153651,
        "text": "sound"
      },
      {
        "startInSeconds": 3.178639,
        "endInSeconds": 3.498821,
        "text": "and"
      },
      {
        "startInSeconds": 3.52381,
        "endInSeconds": 3.924898,
        "text": "picture"
      },
      {
        "startInSeconds": 3.949887,
        "endInSeconds": 4.406712,
        "text": "together."
      }
    ]
  },
  "ranking-closing": {
    "audioUrl": "demo/audio/ranking-closing.wav",
    "durationInSeconds": 3.6184126984126985,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.411655,
        "text": "Three"
      },
      {
        "startInSeconds": 0.436644,
        "endInSeconds": 0.881043,
        "text": "building"
      },
      {
        "startInSeconds": 0.906032,
        "endInSeconds": 1.315737,
        "text": "blocks."
      },
      {
        "startInSeconds": 1.495737,
        "endInSeconds": 1.836599,
        "text": "One"
      },
      {
        "startInSeconds": 1.861587,
        "endInSeconds": 2.415102,
        "text": "repeatable"
      },
      {
        "startInSeconds": 2.440091,
        "endInSeconds": 2.84898,
        "text": "video"
      },
      {
        "startInSeconds": 2.873968,
        "endInSeconds": 3.318413,
        "text": "pipeline."
      }
    ]
  },
  "captioned-video": {
    "audioUrl": "demo/audio/captioned-video.wav",
    "durationInSeconds": 8.784761904761904,
    "captions": [
      {
        "startInSeconds": 0.12,
        "endInSeconds": 0.443401,
        "text": "This"
      },
      {
        "startInSeconds": 0.46839,
        "endInSeconds": 0.758005,
        "text": "demo"
      },
      {
        "startInSeconds": 0.782993,
        "endInSeconds": 1.163855,
        "text": "pairs"
      },
      {
        "startInSeconds": 1.188844,
        "endInSeconds": 1.433651,
        "text": "a"
      },
      {
        "startInSeconds": 1.458639,
        "endInSeconds": 1.994376,
        "text": "generated"
      },
      {
        "startInSeconds": 2.019365,
        "endInSeconds": 2.428254,
        "text": "video"
      },
      {
        "startInSeconds": 2.453243,
        "endInSeconds": 2.803583,
        "text": "with"
      },
      {
        "startInSeconds": 2.828571,
        "endInSeconds": 3.199274,
        "text": "word"
      },
      {
        "startInSeconds": 3.224263,
        "endInSeconds": 3.836644,
        "text": "captions."
      },
      {
        "startInSeconds": 4.016644,
        "endInSeconds": 4.376508,
        "text": "Every"
      },
      {
        "startInSeconds": 4.401497,
        "endInSeconds": 4.790612,
        "text": "asset"
      },
      {
        "startInSeconds": 4.815601,
        "endInSeconds": 5.094422,
        "text": "is"
      },
      {
        "startInSeconds": 5.11941,
        "endInSeconds": 5.569932,
        "text": "bundled."
      },
      {
        "startInSeconds": 5.749932,
        "endInSeconds": 6.16458,
        "text": "Clone"
      },
      {
        "startInSeconds": 6.189569,
        "endInSeconds": 6.423537,
        "text": "the"
      },
      {
        "startInSeconds": 6.448526,
        "endInSeconds": 6.968027,
        "text": "project"
      },
      {
        "startInSeconds": 6.993016,
        "endInSeconds": 7.313197,
        "text": "and"
      },
      {
        "startInSeconds": 7.338186,
        "endInSeconds": 7.749887,
        "text": "render"
      },
      {
        "startInSeconds": 7.774875,
        "endInSeconds": 7.998957,
        "text": "it"
      },
      {
        "startInSeconds": 8.023946,
        "endInSeconds": 8.484762,
        "text": "locally."
      }
    ]
  }
};
